p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTCustomer__c/BBTCustomer__c.object-meta.xml
<CustomObject>
    <label>BBTCustomer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BBTCustomers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/BBTProduct__c.object-meta.xml
<CustomObject>
    <label>BBT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BBT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Image_Alt_Tag__c.field-meta.xml
<CustomField>
    <fullName>Image_Alt_Tag__c</fullName>
    <label>Image Alt Tag</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <label>Image URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <label>Product Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Product_Style__c.field-meta.xml
<CustomField>
    <fullName>Product_Style__c</fullName>
    <label>Product Style</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>mens</fullName>
                <default>true</default>
                <label>mens</label>
            </value>
            <value>
                <fullName>men</fullName>
            </value>
            <value>
                <fullName>men&apos;s</fullName>
            </value>
            <value>
                <fullName>man</fullName>
            </value>
            <value>
                <fullName>mans</fullName>
            </value>
            <value>
                <fullName>man&apos;s</fullName>
            </value>
            <value>
                <fullName>women</fullName>
            </value>
            <value>
                <fullName>womens</fullName>
            </value>
            <value>
                <fullName>woman</fullName>
            </value>
            <value>
                <fullName>womans</fullName>
            </value>
            <value>
                <fullName>woman&apos;s</fullName>
            </value>
            <value>
                <fullName>classic</fullName>
            </value>
            <value>
                <fullName>antique</fullName>
            </value>
            <value>
                <fullName>fancy</fullName>
            </value>
            <value>
                <fullName>digital</fullName>
            </value>
            <value>
                <fullName>analog</fullName>
            </value>
            <value>
                <fullName>analogue</fullName>
            </value>
            <value>
                <fullName>smart</fullName>
            </value>
            <value>
                <fullName>smart watch</fullName>
            </value>
            <value>
                <fullName>sports</fullName>
            </value>
            <value>
                <fullName>sport</fullName>
            </value>
            <value>
                <fullName>pocket</fullName>
            </value>
            <value>
                <fullName>pocket watch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/CustomerOrder__c/CustomerOrder__c.object-meta.xml
<CustomObject>
    <label>CustomerOrder</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CustomerOrder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CustomerOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/CustomerOrder__c/fields/BBTCustomerId__c.field-meta.xml
<CustomField>
    <fullName>BBTCustomerId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>BBT Customers</description>
    <label>BBTCustomerId</label>
    <referenceTo>BBTCustomer__c</referenceTo>
    <relationshipLabel>CustomerOrders</relationshipLabel>
    <relationshipName>CustomerOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/CustomerOrder__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Paid Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Paid Completed</fullName>
            </value>
            <value>
                <fullName>Customizing</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Out For Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/OrderLineItem__c.object-meta.xml
<CustomObject>
    <label>OrderLineItem</label>
    <nameField>
        <label>OrderLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderId</label>
    <referenceTo>CustomerOrder__c</referenceTo>
    <relationshipLabel>OrderLineItems</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductId</label>
    <referenceTo>BBTProduct__c</referenceTo>
    <relationshipLabel>OrderLineItems</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/fields/Quantity_c__c.field-meta.xml
<CustomField>
    <fullName>Quantity_c__c</fullName>
    <label>Quantity__c</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/classes/OrderLineItemTrigger_Test.cls
@isTest
public with sharing class OrderLineItemTrigger_Test {
    
    static final Integer testQuantity = 1;
    static final Integer failQuantity = 0;
   
    static final String  testProductName  = 'Kazuha Ultima';
    static final String  testProductAlt   = 'Kazuha Ultima Watch';
    static final String  testProductURL   = 'imgur.com/fakeLink';
    static final String  testProductStyle = 'mens;men';
    static final Integer testProductPrice = 120;

    static final String testCustomerName = 'Maryland';
    static final String testOrderStatus = 'In Progress';

    @TestSetup
    static void makeData(){
        BBTProduct__c testProd = new BBTProduct__c();
        BBTCustomer__c testCust = new BBTCustomer__c();
        CustomerOrder__c testOrd = new CustomerOrder__c();
        
        testProd.Name = testProductName;
        testProd.Image_Alt_Tag__c = testProductAlt;
        testProd.Image_URL__c = testProductURL;
        testProd.Product_Style__c = testProductStyle;
        testProd.Product_Price__c = testProductPrice;
        insert testProd;

        testCust.Name = testCustomerName;
        insert testCust;

        testOrd.Order_Status__c = testOrderStatus;
        testOrd.BBTCustomerId__c = testCust.Id;
        insert testOrd;

    }

    @isTest 
    static void negativeQuantityTest()
    {
        BBTProduct__c testProd = new BBTProduct__c();
        BBTCustomer__c testCust = new BBTCustomer__c();
        CustomerOrder__c testOrd = new CustomerOrder__c();

        testProd = [SELECT Id FROM BBTProduct__c WHERE Name = :testProductName][0];
        testCust = [SELECT Id FROM BBTCustomer__c WHERE Name = :testCustomerName][0];
        testOrd = [SELECT Id FROM CustomerOrder__c WHERE BBTCustomerId__c = :testCust.Id][0];

        OrderLineItem__c testItem = new OrderLineItem__c();
        testItem.ProductId__c = testProd.Id;
        testItem.OrderId__c = testOrd.Id;
        testItem.Quantity_c__c = testQuantity;

        OrderLineItem__c testItemFail = new OrderLineItem__c();
        testItemFail.ProductId__c = testProd.Id;
        testItemFail.OrderId__c = testOrd.Id;
        testItemFail.Quantity_c__c = failQuantity;

        try 
        {
            insert testItem;
            System.assert(testItem.Id != null, 'Test Line Item successfully inserted');
        }
        catch (Exception e)
        {
            System.assert(false, 'Invalid Insert');
        }

        try 
        {
            insert testItemFail;
        }
        catch (Exception e)
        {
            System.assert(e.getMessage()!= null, 'Trigger responded with error of negative value');
        }

    }
    
}