p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTCustomer__c/BBTCustomer__c.object-meta.xml
<CustomObject>
    <label>BBTCustomer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BBTCustomers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTCustomer__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Id</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BBTCustomers</relationshipName>
    <type>Lookup</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/classes/CreateCustomer.cls
public with sharing class CreateCustomer {
    @AuraEnabled
    public static String createCustomer(String inName, String inEmail) {

        // store the User ID to create a lookup field with
        String inUserId = userInfo.getUserId();

        try
        {
            // create a customer and set values as necessary
            BBTCustomer__c insertCustomer = new BBTCustomer__c();
            insertCustomer.Name = inName;
            insertCustomer.Customer_Email__c = inEmail;
            insertCustomer.User_Id__c = inUserId;

            
            insert insertCustomer;          // try to insert the new customer
            return (insertCustomer.ID);     // and if successful, return the ID
        }
        catch(Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }

    }
}