p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTCustomer__c/BBTCustomer__c.object-meta.xml
<CustomObject>
    <label>BBTCustomer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BBTCustomers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/BBTProduct__c.object-meta.xml
<CustomObject>
    <label>BBT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BBT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/BBTProductDescription__c.field-meta.xml
<CustomField>
    <fullName>BBTProductDescription__c</fullName>
    <description>BBT Product Description</description>
    <label>BBTProductDescription</label>
    <type>TextArea</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Image_Alt_Tag__c.field-meta.xml
<CustomField>
    <fullName>Image_Alt_Tag__c</fullName>
    <label>Image Alt Tag</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <label>Image URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <label>Product Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/BBTProduct_Review__c.object-meta.xml
<CustomObject>
    <label>BBTProduct Review</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>BBTProduct Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BBTProduct Review(s)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/BBT_Product__c.field-meta.xml
<CustomField>
    <fullName>BBT_Product__c</fullName>
    <label>BBT Product</label>
    <referenceTo>BBTProduct__c</referenceTo>
    <relationshipLabel>BBTProduct Review(s)</relationshipLabel>
    <relationshipName>BBTProduct_Review_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/BBTCustomer__c.field-meta.xml
<CustomField>
    <fullName>BBTCustomer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BBTCustomer</label>
    <referenceTo>BBTCustomer__c</referenceTo>
    <relationshipLabel>BBTProduct Review(s)</relationshipLabel>
    <relationshipName>BBTProduct_Review_s</relationshipName>
    <type>Lookup</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>BBTCustomer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/Review_Content__c.field-meta.xml
<CustomField>
    <fullName>Review_Content__c</fullName>
    <label>Review Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/Review_Stars__c.field-meta.xml
<CustomField>
    <fullName>Review_Stars__c</fullName>
    <label>Review Stars</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
                <default>true</default>
                <label>5</label>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/classes/ProductReviewTest.cls
@isTest
public with sharing class ProductReviewTest {
    //testing values
    private static String testNumberStars='2';
    private static String testReviewContent='stupid watch';
    private static String testProductName='Beff Jezos';
    private static Integer testProductPrice=100;
    private static String testCustomerName='Steve Jobs Ex Wife';

    @TestSetup
    static void makeData(){

        List<BBTProduct_Review__c> reviewList= new List<BBTProduct_Review__c>();
        String testStars=testNumberStars;
        String testContent=testReviewContent;
        
        BBTProduct__c testProduct= new BBTProduct__c();
        testProduct.Name=testProductName;
        testProduct.Product_Price__c = testProductPrice;
        
        //these next values are not tested for but required for product insertion
        testProduct.Image_Alt_Tag__c='a';
        testProduct.Image_URL__c='a';
        testProduct.BBTProductDescription__c='a';

        insert testProduct;
 

        BBTCustomer__c testCustomer= new BBTCustomer__c();
        testCustomer.Name=testCustomerName;
        insert testCustomer;


        for(Integer i=0; i<5;i++){
            BBTProduct_Review__c rev=new BBTProduct_Review__c(); 
            rev.Review_Stars__c=testStars;
            rev.Review_Content__c=testContent;
            rev.BBT_Product__c=testProduct.Id;
            rev.BBTCustomer__c=testCustomer.Id;

            reviewList.add(rev);
        }

        insert reviewList;


    }

    @isTest
    static void getLimitedReviewsTest(){
        List<BBTProduct_Review__c> actualReviewList= new List<BBTProduct_Review__c>();
        BBTProduct__c product=new BBTProduct__c();
        product=[SELECT Id FROM BBTProduct__c WHERE NAME=:testProductName][0];
        actualReviewList=ProductReview.getLimitedReviews(product.Id);
        for(BBTProduct_Review__c review: actualReviewList){
            System.assertEquals(testNumberStars, review.Review_Stars__c);
            System.assertEquals(testCustomerName, review.Customer_Name__c);
            System.assertEquals(testReviewContent, review.Review_Content__c);
            System.assert(review.Id!=null, 'comprehensive testing amirite?');
        }

        try{
            List<BBTProduct_Review__c> intentionalFailure= ProductReview.getLimitedReviews('fakeID');
        }
        catch(Exception e){
            System.assert(e.getMessage() != null, 'Exception handled by class' );
        }



    }

}