force-app/main/default/objects/Customer_Order__c/Customer_Order__c.object-meta.xml
<CustomObject>
    <label>Customer Order</label>
    <nameField>
        <displayFormat>ON-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Out For Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

p1_final_site/force-app/main/default/classes/UpdateTriggerHelper.cls
public without sharing class UpdateTriggerHelper {
    public UpdateTriggerHelper() {

    }

    // TODO: make this dynamic
    public Set<String> getStatusVals()
    {
        // create set of String values of expected and valid
        // picklist values, return them
        // using set due to .contains() method
        Set<String> validVals = new Set<String>();

        validVals.add('Cancelled');
        validVals.add('Delivered');
        validVals.add('Out For Delivery');
        validVals.add('Packaging');
        validVals.add('Pending');

        return validVals;
    }

    public Boolean isValidStatusVal(List<Customer_Order__c> inRecs)
    {
        // receive list of Customer Orders, return true if the (new) order
        // status is within valid values
        // currently only accesses the first (and only) Order in the List,
        // but left as list for future scalability
        return (getStatusVals().contains(inRecs[0].Order_Status__c));
    }
}