force-app/main/default/objects/Customer_Order__c/Customer_Order__c.object-meta.xml
<CustomObject>
    <label>Customer Order</label>
    <nameField>
        <displayFormat>ON-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Out For Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancelTriggerHelper.cls
public with sharing class CancelTriggerHelper {
    public CancelTriggerHelper() {

    }

    public Set<String> getCancelVals()
    {
        Set<String> validVals = new Set<String>();

        validVals.add('Cancelled');
        validVals.add('Delivered');
        validVals.add('Out For Delivery');
        validVals.add('Packaging');
        validVals.add('Pending');

        return validVals;
    }

    public Boolean isValidStatusVal(List<Customer_Order__c> inRecs)
    {
        System.debug('Records Received: ');
        System.debug(inRecs);
		System.debug('Compare Received Status to Picklist Vals');
		System.debug(getCancelVals().contains(inRecs[0].Order_Status__c));
        
        return (getCancelVals().contains(inRecs[0].Order_Status__c));
    }
}