p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/BBTProduct_Review__c.object-meta.xml
<CustomObject>
    <label>BBTProduct Review</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>BBTProduct Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BBTProduct Review(s)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/Review_Content__c.field-meta.xml
<CustomField>
    <fullName>Review_Content__c</fullName>
    <label>Review Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/Review_Stars__c.field-meta.xml
<CustomField>
    <fullName>Review_Stars__c</fullName>
    <label>Review Stars</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
                <default>true</default>
                <label>5</label>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/classes/productTriggerTest.cls
@isTest
public with sharing class productTriggerTest {
    

    @isTest
    public static void triggerTest(){
        //show the Review number, customer name, stars, and content for test case

        BBTProduct_Review__c review = new BBTProduct_Review__c();
        BBTProduct_Review__c review2 = new BBTProduct_Review__c();
        
        //intentionally create a review that triggers the trigger
        //trigger triggers on empty content and 1 or 2 stars, asks customer to leave their feedback
        review.Review_Content__c='';
        review.Review_Stars__c='1';


        review2.Review_Content__c='';
        review2.Review_Stars__c='2';

        
        try{
            insert review; 
            //System.assert(true);
        }
        catch(Exception e){
            //System.debug(e.getMessage());
            System.assert(e.getMessage()!=null, 'error handled by class');
        }

        try{
            insert review2; 
            //System.assert(true);
        }
        catch(Exception e){
            //System.debug(e.getMessage());
            System.assert(e.getMessage()!=null, 'error handled by class');
        }

    }  //end test method
}//end class