p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/BBTProduct_Review__c.object-meta.xml
<CustomObject>
    <label>BBTProduct Review</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>BBTProduct Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BBTProduct Review(s)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/BBT_Product__c.field-meta.xml
<CustomField>
    <fullName>BBT_Product__c</fullName>
    <label>BBT Product</label>
    <referenceTo>BBTProduct__c</referenceTo>
    <relationshipLabel>BBTProduct Review(s)</relationshipLabel>
    <relationshipName>BBTProduct_Review_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <formula>BBTCustomer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/Review_Content__c.field-meta.xml
<CustomField>
    <fullName>Review_Content__c</fullName>
    <label>Review Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct_Review__c/fields/Review_Stars__c.field-meta.xml
<CustomField>
    <fullName>Review_Stars__c</fullName>
    <label>Review Stars</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
                <default>true</default>
                <label>5</label>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/classes/ProductReview.cls
//written by Patrick Sepnio, reviewed by Eli Couture
public with sharing class ProductReview {
    static final Integer RECORDS_TO_RETURN=3; //limit of reviews to return to LWC

    @AuraEnabled
    public static List<BBTProduct_Review__c> getLimitedReviews(String inProductId){

        // create a list to store our reviews in
        List<BBTProduct_Review__c> returnReviews = new List<BBTProduct_Review__c>();

        try
        {
            // select our relevant information, filtering by the product ID sent in as parameters
            // always only return 3.
            returnReviews=[SELECT ID, Review_Stars__c,Customer_Name__c ,Review_Content__c
                            FROM BBTProduct_Review__c
                            WHERE BBT_Product__c = :inProductId
                            LIMIT :RECORDS_TO_RETURN];
                            
            // as long as we HAVE a review, send the list back
            if (returnReviews.size()>0) 
            {
                return returnReviews;
            }
            else
            {
                throw new AuraHandledException('No reviews found for product.');
            }
        }   
        catch(Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }
}