p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/BBTProduct__c.object-meta.xml
<CustomObject>
    <label>BBT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BBT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/CustomerOrder__c/CustomerOrder__c.object-meta.xml
<CustomObject>
    <label>CustomerOrder</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CustomerOrder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CustomerOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/CustomerOrder__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Paid Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Paid Completed</fullName>
            </value>
            <value>
                <fullName>Customizing</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Out For Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/OrderLineItem__c.object-meta.xml
<CustomObject>
    <label>OrderLineItem</label>
    <nameField>
        <label>OrderLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderId</label>
    <referenceTo>CustomerOrder__c</referenceTo>
    <relationshipLabel>OrderLineItems</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductId</label>
    <referenceTo>BBTProduct__c</referenceTo>
    <relationshipLabel>OrderLineItems</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/fields/Quantity_c__c.field-meta.xml
<CustomField>
    <fullName>Quantity_c__c</fullName>
    <label>Quantity__c</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/classes/CartListController.cls
/********************************************
* Author: Matthew Jeffery
* Created: 3/6/2022
* Purpose: Apex Controller for cartList
* Aura component
*
*********************************************/
public without sharing class CartListController {

    //Get list of products for an order
    // Requires string input of the orderId
    @AuraEnabled
    public static CustomerOrder__c getOrder(String orderId)
    {
        try 
        {
            // Gets cart info for each item in the current cart id for display
            List<CustomerOrder__c> customerOrders = [SELECT Id, 
                                                        (SELECT ProductId__c, ProductId__r.Name, ProductId__r.Image_URL__c,ProductId__r.Image_Alt_Tag__c, ProductId__r.Product_Price__c, Quantity_c__c 
                                                            FROM OrderLineItems__r) 
                                                    FROM CustomerOrder__c 
                                                    WHERE Id=:orderId];
            if (customerOrders.size() > 0)
            {
                return customerOrders[0];
            }
            else 
            {
                throw new AuraHandledException('No Matching Records Found');
            }
        }
        catch (Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }
    /*
    @AuraEnabled
    public static Boolean submitOrder(String orderId)
    {
        try 
        {
            CustomerOrder__c currentOrder = [SELECT Id, Name, Order_Status__c FROM CustomerOrder__c WHERE id=:orderId];
            currentOrder.Order_Status__c = 'Submitted';
            update currentOrder;
            return true;
        } 
        catch (Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }*/

    @AuraEnabled
    public static String getUserIdPlease()
    {
        return userInfo.getUserId();
    }
}