p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/BBTProduct__c.object-meta.xml
<CustomObject>
    <label>BBT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BBT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <label>Product Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/CustomerOrder__c/CustomerOrder__c.object-meta.xml
<CustomObject>
    <label>CustomerOrder</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CustomerOrder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CustomerOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/CustomerOrder__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Paid Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Paid Completed</fullName>
            </value>
            <value>
                <fullName>Customizing</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Out For Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/CustomerOrder__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Id</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CustomerOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/OrderLineItem__c.object-meta.xml
<CustomObject>
    <label>OrderLineItem</label>
    <nameField>
        <label>OrderLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderId</label>
    <referenceTo>CustomerOrder__c</referenceTo>
    <relationshipLabel>OrderLineItems</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductId</label>
    <referenceTo>BBTProduct__c</referenceTo>
    <relationshipLabel>OrderLineItems</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/OrderLineItem__c/fields/Quantity_c__c.field-meta.xml
<CustomField>
    <fullName>Quantity_c__c</fullName>
    <label>Quantity__c</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/classes/AddProductToCartController.cls
public with sharing class AddProductToCartController {

    String cartId;

    @AuraEnabled
    public static string addProductToCart(String productId, String cartId, Decimal quantity) 
    {
        try 
        {
            // create a new record for a junction object with its Master-Detail Lookups set accordingly
            OrderLineItem__c productLineItem = new OrderLineItem__c(ProductId__c=productId, OrderId__c=cartId, Quantity_c__c=quantity);

            insert productLineItem;         // try to insert the new junction record
            return productLineItem.Id;    // return back the id of the junction record
        } 
        catch (Exception e) 
        {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string createCart(String inUserId)
    {
        try 
        {
            // Create cart
            CustomerOrder__c cart = new CustomerOrder__c();

            // set the cart's lookup to User (you must be logged in to use the site currently, so we use this to track whose logged in)
            // there are no anonymous users here at Big Brother Watches... I mean Big Brother Timepieces
            cart.User_Id__c = inUserId;//UserInfo.getUserId();//inUserId;
            cart.Order_Status__c = 'In Progress';

            
            insert cart;        // try to insert our cart
            return cart.Id;     // return back the id of our order/cart
        } 
        catch (Exception e) 
        {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    public static Decimal getProductPrice(String productId) 
    {
        try
        {
            // create a list to store our products in
            List<BBTProduct__c> productList = new List<BBTProduct__c>();
    
            // select our products based off Id, should always return 1, but the code wants a List
            productList = [SELECT Id, Name, Product_Price__c FROM BBTProduct__c WHERE Id=:productId LIMIT 1];
    
            // as long as we have a product returned from our SOQL, send back the price
            if(productList.size() > 0)
            {
                return productList[0].Product_Price__c;
            }
            else 
            {
                throw new AuraHandledException('No matching records found with Id');
            }
        }
        catch(Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }
}