p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/BBTProduct__c.object-meta.xml
<CustomObject>
    <label>BBT Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BBT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Image_Alt_Tag__c.field-meta.xml
<CustomField>
    <fullName>Image_Alt_Tag__c</fullName>
    <label>Image Alt Tag</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <label>Image URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <label>Product Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/objects/BBTProduct__c/fields/Product_Style__c.field-meta.xml
<CustomField>
    <fullName>Product_Style__c</fullName>
    <label>Product Style</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>mens</fullName>
                <default>true</default>
                <label>mens</label>
            </value>
            <value>
                <fullName>men</fullName>
            </value>
            <value>
                <fullName>men&apos;s</fullName>
            </value>
            <value>
                <fullName>man</fullName>
            </value>
            <value>
                <fullName>mans</fullName>
            </value>
            <value>
                <fullName>man&apos;s</fullName>
            </value>
            <value>
                <fullName>women</fullName>
            </value>
            <value>
                <fullName>womens</fullName>
            </value>
            <value>
                <fullName>woman</fullName>
            </value>
            <value>
                <fullName>womans</fullName>
            </value>
            <value>
                <fullName>woman&apos;s</fullName>
            </value>
            <value>
                <fullName>classic</fullName>
            </value>
            <value>
                <fullName>antique</fullName>
            </value>
            <value>
                <fullName>fancy</fullName>
            </value>
            <value>
                <fullName>digital</fullName>
            </value>
            <value>
                <fullName>analog</fullName>
            </value>
            <value>
                <fullName>analogue</fullName>
            </value>
            <value>
                <fullName>smart</fullName>
            </value>
            <value>
                <fullName>smart watch</fullName>
            </value>
            <value>
                <fullName>sports</fullName>
            </value>
            <value>
                <fullName>sport</fullName>
            </value>
            <value>
                <fullName>pocket</fullName>
            </value>
            <value>
                <fullName>pocket watch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

p2_final_site/revature-alchemy-project-2/force-app/main/default/classes/GetIndvProductInfo_Test.cls
@isTest
public with sharing class GetIndvProductInfo_Test {
   
    
    static final String  testProductName  = 'Kazuha Ultima';
    static final String  testProductAlt   = 'Kazuha Ultima Watch';
    static final String  testProductURL   = 'imgur.com/fakeLink';
    static final String  testProductStyle = 'mens;men';
    static final Integer testProductPrice = 120;
    static final String  intentionalFail  = 'intentionalFailureId';

    static final Integer RECORDS_TO_MAKE = 5;

    @TestSetup
    static void makeData()
    {
        List<BBTProduct__c> prodList = new List<BBTProduct__c>();
        
        // create 13, since we want to test LIMIT 12 and OFFSET 12
        for(Integer i = 0; i < RECORDS_TO_MAKE; i++)
        {
            BBTProduct__c prod = new BBTProduct__c();
            prod.Name = testProductName;
            prod.Image_Alt_Tag__c = testProductAlt;
            prod.Image_URL__c = testProductURL;
            prod.Product_Style__c = testProductStyle;
            prod.Product_Price__c = testProductPrice;

            prodList.add(prod);
        }

        insert prodList;
    }

    @isTest
    static void getProductTest()
    {
        List<BBTProduct__c> actualProducts = new List<BBTProduct__c>();
        List<BBTProduct__c> testProducts = new List<BBTProduct__c>();

        while(testProducts.size() <= RECORDS_TO_MAKE)
        {
            List<BBTProduct__c> tempProd = new List<BBTProduct__c>();
            Integer offset = 0;
            String dynQuery = 'SELECT Id FROM BBTProduct__c LIMIT 1';

            if(offset > 0)
            {
                tempProd = Database.query(dynQuery);
                testProducts.add(tempProd[0]);
            }
            else 
            {
                dynQuery += ' OFFSET ' + offset;
                tempProd = Database.query(dynQuery);
                testProducts.add(tempProd[0]);
            }
        }

        for(BBTProduct__c prod : testProducts)
        {
            actualProducts.add(GetIndvProductInfo.getProduct(prod.Id));
        }

        for(BBTProduct__c prod : actualProducts)
        {
            System.assertEquals(testProductName, prod.Name);
            System.assertEquals(testProductAlt, prod.Image_Alt_Tag__c);
            System.assertEquals(testProductURL, prod.Image_URL__c);
            System.assertEquals(testProductPrice, prod.Product_Price__c);
        }

        try
        {
            BBTProduct__c failProd = GetIndvProductInfo.getProduct(intentionalFail);
        }
        catch (Exception e)
        {
            System.assert(e.getMessage()!= null, 'error handled by component');
        }

    }
}