force-app/main/default/objects/Artisan__c/Artisan__c.object-meta.xml
<CustomObject>
    <description>Artisan to create product colors</description>
    <label>Artisan</label>
    <nameField>
        <displayFormat>RSART-{00000}</displayFormat>
        <label>Artisan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Artisans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artisan__c/fields/Artist_Name__c.field-meta.xml
<CustomField>
    <fullName>Artist_Name__c</fullName>
    <description>Name of Artisan</description>
    <label>Artist Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artisan__c/fields/ColorFor__c.field-meta.xml
<CustomField>
    <fullName>ColorFor__c</fullName>
    <description>Color that this artisan is responsible for</description>
    <label>ColorFor</label>
    <length>48</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

p1_final_site/force-app/main/default/classes/ColorTestController.cls
public with sharing class ColorTestController {

    @AuraEnabled(cacheable=true)
    public static string getArtisanName(string colorType){
        Artisan__c artisanName;
        try {
            artisanName = [SELECT Name, Artist_Name__c FROM Artisan__C where ColorFor__c = :colorType];
            System.debug(artisanName.Artist_Name__c);
            return artisanName.Artist_Name__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}